export enum WidgetsTypes {
  RECTANGLE = 'rectangle',
  ELLIPSE = 'ellipse',
  TEXT = 'text',
  SWIPE_UP = 'swipe_up',
  SLIDER = 'slider',
  QUESTION = 'question',
  CLICK_ME = 'click_me',
  TALK_ABOUT = 'talk_about',
  EMOJI_REACTION = 'emoji_reaction',
  TIMER = 'timer',
  CHOOSE_ANSWER = 'choose_answer',
  GIPHY = 'giphy',
  QUIZ_ONE_ANSWER = 'quiz_one_answer',
  QUIZ_MULTIPLE_ANSWERS = 'quiz_multiple_answers',
  QUIZ_OPEN_ANSWER = 'quiz_open_answer',
  QUIZ_MULTIPLE_ANSWER_WITH_IMAGE = 'quiz_one_multiple_with_image',
  QUIZ_RATE = 'quiz_rate',
}
